name: 'Add Nuget Source'
description: 'Adds public NuGet source if it is not already added.'

runs:
  using: "composite"
  steps:
    - name: Add Nuget sources
      shell: powershell
      run: |
        Write-Host "Configuring NuGet sources..."
        
        # Check and add nuget.org if not present
        $sources = dotnet nuget list source
        if ($sources -notmatch "nuget.org") {
          Write-Host "Adding nuget.org source..."
          dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
        } else {
          Write-Host "nuget.org source already exists"
        }
        
        Write-Host "Public NuGet sources configured successfully"