name: 'Mend SCA Scanner'
description: 'Run Mend SCA scan'
inputs:
  api-key:
    description: 'Mend API key'
    required: true
  dotnet-solution:
    description: 'Solution file path'
    required: true
  scan-target:
    description: 'Scan target'
    required: false
    default: 'default-branch'

runs:
  using: 'composite'
  steps:
    - name: Install Mend CLI
      shell: bash
      run: |
        echo "Installing Mend CLI..."
        curl -LJO https://downloads.mend.io/cli/linux_amd64/mend
        chmod +x mend
        sudo mv mend /usr/local/bin/
        mend --version

    - name: Run Mend Scan
      shell: bash
      env:
        MEND_API_KEY: ${{ inputs.api-key }}
        MEND_URL: https://saas.mend.io
      run: |
        echo "Running Mend scan on: ${{ inputs.dotnet-solution }}"
        PROJECT_NAME=$(basename "${{ inputs.dotnet-solution }}" .sln)
        
        # Run Mend scan
        mend dependencies \
          --dir "$(dirname "${{ inputs.dotnet-solution }}")" \
          --update \
          --non-interactive \
          --project-name "$PROJECT_NAME"
        
        echo "Mend scan completed for $PROJECT_NAME"