name: Mend SCA Scan for default branch

permissions:
  contents: read

on:
  push:
    branches:
      - feature/Adding_Mend_Sonar_Scans
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # manual trigger

jobs:
  mend-sca:
    runs-on: windows-latest
    strategy:
      matrix:
        solution:
          - SignIn/SignIn.sln
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Add NuGet sources
        uses: ./.github/actions/nuget-source
        continue-on-error: true

      - name: Setup nuget.exe
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: latest

      - name: Restore NuGet Packages
        run: dotnet restore "${{ matrix.solution }}"
        
      - name: Mend SCA Scan
        uses: ./.github/actions/mend-sca-scanner
        with:
          api-key: ${{secrets.TC_WHITESOURCE_API_KEY}}
          mend-email: ${{secrets.TC_MEND_EMAIL}}
          scan-target: default-branch
          dotnet-solution: ${{ matrix.solution }}
          config-file: whitesource.config